# The port that the relay will listen on to receive SMTP e-mail messages, the default is 25. 
# No authorization is required when connecting to this port, 
# but if necessary, select the basic authentication method with a fake username and password
SmtpPort: 25
# Your token for the Telegram bot, get it at https://t.me/BotFather when registering the bot
TelegramBotToken: SPECIFY THERE TELEGRAM BOT TOKEN
# Define here a list of email addresses and telegram chats that will receive emails sent to these addresses.
# Use an asterisk "*" instead of an email address to send all emails to some telegram chat
# For Telegram chats that are group or channel chats, add a minus in front of the chat ID
Routing:
-   Email: "*"
    TelegramChat: SPECIFY THERE TELEGRAM CHATID OR @USERNAME
-   Email: example@test.com
    TelegramChat: SPECIFY THERE TELEGRAM CHATID OR @USERNAME
# Logging Level. Set to Debug to see the details of the communication between your mail program and the relay.
# Set to Error to see less information
Logging:
  LogLevel:
    Default: Debug
